-- Local dev seed data — mirrors what's already loaded in the production D1
-- database. Run with: wrangler d1 execute tazecode-db --local --file=seed.sql

INSERT INTO admin_users (username, password_hash) VALUES ('admin', 'eeeea69c84c1d95e47cd9c48de1f32dbc0fb60c0c8feac306fda2ed4ea882f0c');

INSERT INTO projects (slug, name, category, year, client, role, duration, description, problem, solution, features, challenges, result, tech, live, github, thumbnail_url, featured, sort_order) VALUES ('kasir-warung-pos', 'Kasir Warung — POS System', 'POS / Kasir', '2025', 'UMKM Warung Kelontong (Personal Project)', 'Full Stack Developer', '3 weeks', 'Sistem kasir sederhana untuk warung kelontong dengan manajemen stok, transaksi, dan laporan harian.', 'Pemilik warung mencatat transaksi dan stok secara manual di buku, sehingga rawan salah hitung dan sulit melihat laporan penjualan bulanan.', 'Dibangun aplikasi kasir berbasis web yang bisa diakses dari satu perangkat di kasir, dengan pencatatan transaksi otomatis dan laporan stok real-time.', '["Input transaksi cepat dengan pencarian produk","Manajemen stok otomatis saat transaksi tersimpan","Laporan penjualan harian dan bulanan","Role akses untuk kasir dan pemilik","Cetak struk sederhana"]', 'Menjaga akurasi stok saat terjadi transaksi ganda dalam waktu bersamaan, diselesaikan dengan locking transaksi di level database.', 'Waktu pencatatan transaksi berkurang, dan pemilik warung dapat memantau stok tanpa menghitung manual di akhir hari.', '["Laravel","MySQL","Tailwind CSS","Alpine.js"]', '', '', '', 1, 0);
INSERT INTO projects (slug, name, category, year, client, role, duration, description, problem, solution, features, challenges, result, tech, live, github, thumbnail_url, featured, sort_order) VALUES ('rentalku-motor-rental', 'Rentalku — Motor Rental System', 'Rental System', '2025', 'Client Project', 'Full Stack Developer', '1 month', 'Platform penyewaan motor dengan jadwal ketersediaan unit, booking online, dan integrasi pembayaran.', 'Proses booking motor sewa masih dilakukan lewat chat manual, sering terjadi bentrok jadwal antar penyewa.', 'Dibangun sistem booking dengan kalender ketersediaan unit per hari dan status pembayaran otomatis lewat payment gateway.', '["Kalender ketersediaan unit motor","Booking online dengan konfirmasi otomatis","Integrasi pembayaran (Midtrans)","Dashboard admin untuk kelola unit dan pemesanan","Notifikasi email saat status booking berubah"]', 'Mencegah double booking pada unit yang sama saat dua user memesan bersamaan, diselesaikan dengan validasi jadwal di sisi server sebelum konfirmasi.', 'Proses booking berjalan tanpa bentrok jadwal dan admin dapat memantau semua pemesanan dari satu dashboard.', '["Laravel","PostgreSQL","Bootstrap","Midtrans API"]', '', '', '', 1, 1);
INSERT INTO projects (slug, name, category, year, client, role, duration, description, problem, solution, features, challenges, result, tech, live, github, thumbnail_url, featured, sort_order) VALUES ('laundryflow', 'LaundryFlow — Laundry Management', 'Laundry System', '2024', 'Client Project', 'Backend Developer', '3 weeks', 'Sistem manajemen laundry untuk pencatatan order, tracking status cucian, dan notifikasi pelanggan.', 'Pelanggan sering menanyakan status cucian lewat telepon karena tidak ada cara untuk mengecek sendiri.', 'Dibuat sistem tracking order dengan status berjenjang (diterima, dicuci, selesai, diambil) yang bisa dicek pelanggan lewat nomor order.', '["Input order dengan estimasi selesai otomatis","Tracking status order per tahap","Riwayat transaksi pelanggan","Perhitungan harga berdasarkan berat dan layanan"]', 'Merancang struktur status order yang fleksibel untuk berbagai jenis layanan (cuci kering, setrika, express).', 'Pertanyaan status cucian lewat telepon berkurang karena pelanggan bisa mengecek sendiri secara online.', '["Node.js","Express","MySQL","React"]', '', '', '', 0, 2);
INSERT INTO projects (slug, name, category, year, client, role, duration, description, problem, solution, features, challenges, result, tech, live, github, thumbnail_url, featured, sort_order) VALUES ('beritalokal-cms', 'BeritaLokal — News Website & CMS', 'News Website', '2024', 'Personal Project', 'Full Stack Developer', '1 month', 'Website berita lokal dengan CMS untuk penulis mengelola artikel, kategori, dan media.', 'Redaksi berita lokal membutuhkan platform sendiri untuk publikasi tanpa bergantung pada platform pihak ketiga.', 'Dibangun CMS custom dengan editor artikel, manajemen kategori, dan halaman publik yang cepat diakses.', '["Editor artikel dengan gambar dan embed","Manajemen kategori dan tag","Role penulis dan editor","Halaman publik dengan pencarian artikel","SEO meta per artikel"]', 'Mengoptimalkan waktu load halaman publik yang berisi banyak gambar artikel.', 'Redaksi dapat mempublikasikan artikel sendiri tanpa bantuan developer untuk setiap update konten.', '["Laravel","MySQL","Tailwind CSS","TinyMCE"]', '', '', '', 0, 3);
INSERT INTO projects (slug, name, category, year, client, role, duration, description, problem, solution, features, challenges, result, tech, live, github, thumbnail_url, featured, sort_order) VALUES ('tokonyaku-ecommerce', 'Tokonyaku — E-Commerce Store', 'E-Commerce', '2024', 'Client Project', 'Full Stack Developer', '6 weeks', 'Toko online untuk UMKM fashion dengan katalog produk, keranjang, dan checkout terintegrasi pembayaran.', 'Penjualan hanya lewat media sosial membuat pemilik toko kesulitan mengelola stok dan pesanan yang masuk dari berbagai chat.', 'Dibangun toko online dengan katalog produk terpusat, keranjang belanja, dan checkout dengan status pesanan yang jelas.', '["Katalog produk dengan varian ukuran/warna","Keranjang dan checkout","Integrasi pembayaran otomatis","Dashboard pesanan untuk admin","Manajemen stok per varian"]', 'Menyusun struktur database varian produk agar tetap sederhana namun fleksibel untuk kombinasi ukuran dan warna.', 'Seluruh pesanan tercatat di satu sistem, mengurangi kesalahan pencatatan stok dari sebelumnya yang manual.', '["Laravel","MySQL","Tailwind CSS","Midtrans API"]', '', '', '', 1, 4);
INSERT INTO projects (slug, name, category, year, client, role, duration, description, problem, solution, features, challenges, result, tech, live, github, thumbnail_url, featured, sort_order) VALUES ('opsdash-dashboard', 'OpsDash — Internal Operations Dashboard', 'Dashboard', '2023', 'Client Project', 'Frontend Developer', '2 weeks', 'Dashboard internal untuk memantau metrik operasional tim lapangan secara real-time.', 'Tim manajemen tidak punya visibilitas terhadap data operasional harian tanpa meminta laporan manual dari tim lapangan.', 'Dibangun dashboard yang menarik data operasional dan menampilkannya dalam grafik dan tabel yang mudah dibaca.', '["Grafik metrik harian dan mingguan","Filter berdasarkan tim dan periode","Ekspor data ke CSV","Update data berkala otomatis"]', 'Menampilkan volume data yang besar tanpa membuat dashboard terasa berat saat dibuka.', 'Manajemen dapat memantau metrik operasional langsung tanpa menunggu laporan manual.', '["React","Node.js","PostgreSQL","Chart.js"]', '', '', '', 0, 5);

INSERT INTO site_settings (key, value) VALUES
('stats_projects', '15'),
('stats_clients', '8'),
('stats_years', '3'),
('stats_tech', '10'),
('contact_whatsapp', '6280000000000'),
('contact_email', 'hello@tazecode.dev'),
('contact_github', 'https://github.com/'),
('contact_linkedin', 'https://linkedin.com/'),
('contact_instagram', '');

INSERT INTO services (title, description, features, sort_order) VALUES
('Jasa Company Profile', 'Website profesional harga terjangkau yang membangun kredibilitas bisnis atau organisasi Anda.', '["Layout multi-section responsif","Konten tersusun jelas","Form kontak & inquiry","Setup SEO dasar"]', 0),
('Jasa Toko Online / E-Commerce', 'Toko online lengkap dengan katalog produk, checkout, dan manajemen pesanan.', '["Katalog produk & varian","Alur keranjang & checkout","Integrasi payment gateway","Dashboard pesanan admin"]', 1),
('Jasa Aplikasi Web Custom', 'Sistem custom — POS, rental, laundry, dashboard internal — sesuai alur kerja bisnis Anda.', '["Model data & logika custom","Akses berbasis role","Laporan & ekspor data","Arsitektur yang bisa berkembang"]', 2),
('Jasa Landing Page', 'Landing page fokus untuk produk, campaign, atau peluncuran layanan — harga bersahabat, hasil maksimal.', '["Layout fokus konversi","Loading cepat","Siap terintegrasi analytics"]', 3),
('Jasa Website Custom', 'Dibangun sepenuhnya sesuai kebutuhan spesifik Anda saat solusi siap pakai tidak cukup.', '["Diskusi kebutuhan mendalam","Arsitektur sesuai kebutuhan","Kolaborasi berkelanjutan"]', 4),
('Jasa Maintenance Website', 'Dukungan berkelanjutan, perbaikan bug, update, dan peningkatan setelah website live.', '["Perbaikan bug & monitoring","Update fitur","Update keamanan & dependency"]', 5);
